version: '3'

services:
  postgres-client:
    image: "postgres:12"
    container_name: "hotel_service_db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hotel_service
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/data/databases/hotel_service
volumes:
  pgdata:
    driver: local
